      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          # 使用 sudo 强制安装到全局，确保机器人一定能找到
          sudo pip3 install --upgrade pip
          sudo pip3 install cython==0.29.33 buildozer virtualenv

      - name: Build with Buildozer
        run: |
          # 这一行最关键：手动把所有可能的路径都加上
          export PATH=$PATH:/usr/local/bin:$HOME/.local/bin
          # 验证 Cython 是不是真的在那
          which cython
          cython --version
          # 开始打包
          yes | buildozer android debug
