name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          # 关键修正：这里安装了 cython 和 virtualenv
          pip3 install --user --upgrade buildozer cython virtualenv

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # 自动接受协议并开始打包
          yes | buildozer android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk
